RazorCRUD/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorCRUD.Models.Contexto;
using RazorCRUD.Models.Entidade;

namespace RazorCRUD.Controllers
{
    public class FuncionariosController : Controller
    {
        /// <summary>
        /// Database context
        /// </summary>
        private readonly Contexto _contexto;
        public FuncionariosController(Contexto contexto)
        {
            _contexto = contexto;
        }

        /// <summary>
        /// Primary method that returns a list of rows in database table "Funcionario"
        /// </summary>
        /// <returns>An object from the type "Funcionario"</returns>
        public IActionResult Index()
        {
            // List the table rows from the database
            var lista = _contexto.Funcionario.ToList();
            return View(lista);
        }

        /// <summary>
        /// Insert the options on dropdown list 
        /// </summary>
        public void CarregaTipoFuncionario()
        {
            var ItensTipoFuncionario = new List<SelectListItem>
            {
                new SelectListItem{ Value ="1", Text ="Gestor"},
                new SelectListItem{ Value ="2", Text ="DBA"},
                new SelectListItem{ Value ="3", Text ="Especialista"},
                new SelectListItem{ Value ="4", Text ="Programador"},
                new SelectListItem{ Value ="5", Text ="Trainee"}
            };
            // Load the items on page
            ViewBag.TiposFuncionario = ItensTipoFuncionario;
        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            var Funcionario = _contexto.Funcionario.Find(Id);
            CarregaTipoFuncionario();
            return View(Funcionario);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var funcionario = new Funcionario();
            CarregaTipoFuncionario();
            return View(funcionario);
        }

        /// <summary>
        /// Send input informations to the database
        /// </summary>
        /// <param name="Funcionario"></param>
        /// <returns>An object from the type "Funcionario" </returns>
        [HttpPost]
        public IActionResult Create(Funcionario Funcionario)
        {
            // Allow the operation when all fields have a value
            if (ModelState.IsValid)
            {
                _contexto.Funcionario.Add(Funcionario);
                _contexto.SaveChanges();

                return RedirectToAction("Index");
            }
            CarregaTipoFuncionario();
            return View(Funcionario);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var Funcionario = _contexto.Funcionario.Find(Id);
            CarregaTipoFuncionario();
            return View(Funcionario);
        }

        /// <summary>
        /// Send the edited informations to the database
        /// </summary>
        /// <param name="Funcionario"></param>
        /// <returns>An object from the type "Funcionario" </returns>
        [HttpPost]
        public IActionResult Edit(Funcionario Funcionario)
        {
            // Allow the operation when all fields have a value
            if (ModelState.IsValid)
            {
                _contexto.Funcionario.Update(Funcionario);
                _contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                CarregaTipoFuncionario();
                return View(Funcionario);
            }
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var Funcionario = _contexto.Funcionario.Find(Id);
            CarregaTipoFuncionario();
            return View(Funcionario);
        }

        /// <summary>
        /// Send the user information to the database end delete the row
        /// </summary>
        /// <param name="Funcionario"></param>
        /// <returns>An object from the type "Funcionario" </returns>
        [HttpPost]
        public IActionResult Delete(Funcionario _Funcionario)
        {
            var Funcionario = _contexto.Funcionario.Find(_Funcionario.Id);
            if (Funcionario != null)
            {
                _contexto.Funcionario.Remove(Funcionario);
                _contexto.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(Funcionario);
        }
    }
}

RazorCRUD/Controllers/SetorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RazorCRUD.Models.Contexto;
using RazorCRUD.Models.Entidade;

namespace RazorCRUD.Controllers
{
    public class SetorController : Controller
    {
        private readonly Contexto _contexto;

        public SetorController(Contexto contexto)
        {
            _contexto = contexto;
        }

        public IActionResult Index()
        {
            var lista = _contexto.Setor.ToList();
            return View(lista);
        }
               

        [HttpGet]
        public IActionResult Details(int Id)
        {
            var setor = _contexto.Setor.Find(Id);
            return View(setor);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var setor = new Setor();
            return View(setor);
        }
            
        [HttpPost]
        public IActionResult Create(Setor Setor)
        {
            
            if (ModelState.IsValid)
            {
                _contexto.Setor.Add(Setor);
                _contexto.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(Setor);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var Setor = _contexto.Setor.Find(Id);
            return View(Setor);
        }

        [HttpPost]
        public IActionResult Edit(Setor Setor)
        {
  
            if (ModelState.IsValid)
            {
                _contexto.Setor.Update(Setor);
                _contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(Setor);
            }
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var Setor = _contexto.Setor.Find(Id);
            return View(Setor);
        }


        [HttpPost]
        public IActionResult Delete(Setor _Setor)
        {
            var Setor = _contexto.Setor.Find(_Setor.Id);
            if (Setor != null)
            {
                _contexto.Setor.Remove(Setor);
                _contexto.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(Setor);
        }
    }
}

RazorCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>@ViewData["Title"] - Funcionários</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionário</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="Setor" asp-action="Index">Setor</a>
                        </li>
             
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Razor Crud - Bruno Rodrigues 7SIAN
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>